# Generated by Django 3.2.16 on 2023-04-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230427_0013'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_unique_set_author_user',
        ),
    ]
